apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  #selector defines what pods should this service should expose
  #so this exposts posts pod - in posts-depl.yaml template -> labels with app:posts
  # so selctor tells to service to find all the pods with the label app:posts and expose to outside world as it nodeport service
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000 #port of service which it listsens on, it can be diffierent port num
      targetPort: 4000 #port of pod which its sends traffic to, it should be what app service is listening on
